# 本番環境設定
database:
  host: "${SUPABASE_HOST}"
  port: 5432
  database: "${SUPABASE_DB}"
  user: "${SUPABASE_USER}"
  password: "${SUPABASE_PASSWORD}"
  ssl_mode: "require"
  
logging:
  level: "INFO"
  log_dir: "/var/log/kado-com"
  max_file_size: 52428800  # 50MB
  backup_count: 10
  
scheduling:
  status_collection_interval: 30  # 分
  history_calculation_hour: 12     # 稼働率計算実行時刻（12時）
  history_calculation_minute: 0    # 稼働率計算実行分
  max_concurrent_businesses: 5     # 稼働状況取得の店舗並行処理数
  max_concurrent_working_rate: 10  # 稼働率計算の並行処理数
  health_check_interval: 15        # 分
  cleanup_time_hour: 2             # 午前2時
  cleanup_time_minute: 0
  misfire_grace_time:
    status_collection: 300  # 5分
    status_history: 600     # 10分
  max_log_retention_days: 30       # ログ保持日数
  business_hours_buffer: 0         # 営業時間バッファ（分）
  
scraping:
  timeout: 30
  retry_attempts: 3
  delay_between_requests: 2
  user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36"
  
# 本番環境固有設定
monitoring:
  health_check_interval: 15  # 分
  alert_email: "admin@kado.com"
  
security:
  encrypt_logs: true
  max_log_retention_days: 30
