# テスト環境設定
database:
  host: "localhost"
  port: 5432
  database: "kado_test"
  user: "test_user"
  password: "test_password"
  
logging:
  level: "DEBUG"
  log_dir: "./test_logs"
  max_file_size: 1048576  # 1MB
  backup_count: 3
  
scheduling:
  status_collection_interval: 5   # 分（テスト用短縮）
  history_calculation_hour: 12     # 稼働率計算実行時刻（12時）
  history_calculation_minute: 0    # 稼働率計算実行分
  max_concurrent_businesses: 2     # 稼働状況取得の店舗並行処理数（テスト用）
  max_concurrent_working_rate: 3   # 稼働率計算の並行処理数（テスト用）
  health_check_interval: 5         # 分（テスト用短縮）
  cleanup_time_hour: 2             # 午前2時
  cleanup_time_minute: 0
  misfire_grace_time:
    status_collection: 60   # 1分（テスト用短縮）
    status_history: 120     # 2分（テスト用短縮）
  max_log_retention_days: 7        # ログ保持日数（テスト用短縮）
  business_hours_buffer: 0         # 営業時間バッファ（分）
  
scraping:
  timeout: 10
  retry_attempts: 2
  delay_between_requests: 0.5
  user_agent: "Test-Agent/1.0"
  
# テスト環境固有設定
testing:
  mock_external_apis: true
  use_test_data: true
  cleanup_after_test: true
